### ISSUE TITLE
Add Forgot password feature

### ISSUE THREAD

**Issue by JeanMMillet** [WildCodeSchool/2309-wns-jaune-wild-code-hub#161]
We need to allow the user to create a new password when he click on forget password
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/73
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/74
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/75
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/76
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/77
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/78
```
