### ISSUE TITLE
Like / dislike Project

### ISSUE THREAD

**Issue by Alexandre78R** [WildCodeSchool/2309-wns-jaune-wild-code-hub#237]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/236
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/235
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/234
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/233
```
