### ISSUE TITLE
Share editor / Mangement User project accesses project

### ISSUE THREAD

**Issue by Alexandre78R** [WildCodeSchool/2309-wns-jaune-wild-code-hub#243]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/229
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/230
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/238
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/239
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/240
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/241
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/242
```
