### ISSUE TITLE
Setting Project Editor

### ISSUE THREAD

**Issue by Alexandre78R** [WildCodeSchool/2309-wns-jaune-wild-code-hub#244]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/231
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/232
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/245
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/246
```
