### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by Alexandre78R** [WildCodeSchool/2309-wns-jaune-wild-code-hub#247]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/248
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/249
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/250
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/251
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/252
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/253
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/254
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/255
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/256
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/257
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/258
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/259
```
