### ISSUE TITLE
Editor code

### ISSUE THREAD

**Issue by Alexandre78R** [WildCodeSchool/2309-wns-jaune-wild-code-hub#4]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/20
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/29
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/27
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/24
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/25
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/23
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/28
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/35
```
