### ISSUE TITLE
Page "list me Project"

### ISSUE THREAD

**Issue by JeanMMillet** [WildCodeSchool/2309-wns-jaune-wild-code-hub#9]
```[tasklist]
### Tasks
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/68
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/69
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/70
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/71
- [ ] https://github.com/WildCodeSchool/2309-wns-jaune-wild-code-hub/issues/72
```
